### ISSUE TITLE
Add support for sendStringParametersAsUnicode property

### ISSUE THREAD

**Issue by mbouchenoire** [r2dbc/r2dbc-mssql#112]
This property is supported by the JDBC driver, allowing *massive* performance improvements in some cases.

**Comment by mp911de** [comment]
Happy to review a pull request to accelerate this enhancement. Right now, we need to investigate what drivers are doing differently on TDS level.

**Comment by mp911de** [comment]
`StringCodec` sends all Character payloads using 2-byte Unicode encoding with `NVARCHAR`/`NCHAR`. `ClobCodec` uses the database collation encoding.

This is due to the lack of type information when to use `VARCHAR` vs. `NVARCHAR`. So you should consider the mentioned option always to be `true`.

**Comment by mbouchenoire** [comment]
`true` is indeed the current value (assuming the option should exist). The fact that this option is not supported yet is a dealbreaker for our project, as the constructed queries cannot use the existing indexes 😢 . 

I will try to work on it but the timing is a bit off for my schedule 😞 .

Thanks for your help !

**Comment by mp911de** [comment]
Introducing `sendStringParametersAsUnicode` with the support of `false` requires minor changes to [`StringCodec`](https://github.com/r2dbc/r2dbc-mssql/blob/master/src/main/java/io/r2dbc/mssql/codec/StringCodec.java#L85) to use the proper charset for encoding and sending the data as binary instead of `TdsDataType.NVARCHAR`/`TdsDataType.NTEXT`.

`RpcParameterContext.in(…)` accepts an optional collation. If the collation is set for `CharSequence` values, then we could take this as an indicator how to encode the `String`. `ParametrizedMssqlStatement` has access to `ConnectionOptions` which seems a good place to transport the config option.
